/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kafka.common.security.scram.internals;

import org.apache.kafka.common.KafkaException;
import org.apache.kafka.common.security.scram.ScramCredential;
import org.apache.kafka.common.security.scram.internals.ScramMessages.ClientFinalMessage;
import org.apache.kafka.common.security.scram.internals.ScramMessages.ClientFirstMessage;
import org.apache.kafka.common.security.scram.internals.ScramMessages.ServerFirstMessage;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/**
 * Scram message salt and hash functions defined in <a href="https://tools.ietf.org/html/rfc5802">RFC 5802</a>.
 */
// SECURITY: SEC-SCRAM-024 (CRITICAL) Central cryptographic utility for SCRAM authentication per RFC 5802.
// Why: Implements PBKDF2 key derivation (hi method), HMAC computation, hash functions, key
// derivation chain (clientKey, storedKey, serverKey), proof/signature generation, and secure
// random nonce/salt generation. This class is the cryptographic foundation of all SCRAM
// authentication in Kafka -- any flaw here compromises the entire SCRAM security model.
// Exploit: If the iteration count passed to hi() is set below the minimum (4096 per RFC 5802
// Section 5.1), offline brute-force of leaked SCRAM credentials becomes feasible. At 4096
// iterations with SHA-256, a single GPU can test ~100K passwords/second; at 100 iterations,
// ~4M/second. At the default 4096, a targeted dictionary attack on a weak password is viable.
// Improvement: (1) Enforce a hard minimum of 4096 iterations at the hi() method level, not
// just at the caller. (2) Consider increasing the default to 16384+ for stronger protection.
// (3) Add parameter validation: reject null/empty salt, zero/negative iterations.
//
// CROSS-CUTTING: Core cryptographic primitive consumed across the SCRAM authentication stack:
// - ScramSaslServer: Uses hmac, hash, clientSignature, serverSignature, storedKey for proof
//   verification and server signature computation.
// - ScramSaslClient: Uses hi (PBKDF2), clientProof, serverKey, serverSignature for proof
//   generation and server verification.
// - ScramCredentialUtils: Indirectly via ScramCredential (generated by generateCredential).
// - metadata/ScramCredentialData: Uses generateCredential for credential creation during
//   KRaft metadata processing.
// Depends on: ScramMechanism for algorithm names (hashAlgorithm, macAlgorithm).
// Depends on: ScramMessages for auth message computation across message types.
// Contract: Instances are NOT thread-safe (MessageDigest and Mac are stateful).
// Impact: Changes to key derivation or HMAC computation break all SCRAM authentication.
public class ScramFormatter {

    private static final Pattern EQUAL = Pattern.compile("=", Pattern.LITERAL);
    private static final Pattern COMMA = Pattern.compile(",", Pattern.LITERAL);
    private static final Pattern EQUAL_TWO_C = Pattern.compile("=2C", Pattern.LITERAL);
    private static final Pattern EQUAL_THREE_D = Pattern.compile("=3D", Pattern.LITERAL);

    private final MessageDigest messageDigest;
    private final Mac mac;
    private final SecureRandom random;

    // DECISION: Uses JCA SecretKeyFactory for PBKDF2 (via Mac) rather than Bouncy Castle or custom.
    // Alternatives: (1) Bouncy Castle PBKDF2 provider, (2) Custom PBKDF2 loop, (3) Argon2id.
    // Rationale: JCA implementation guarantees FIPS compliance when running on a FIPS-certified JVM
    // and benefits from JVM hardware acceleration where available (e.g., Intel AES-NI for HMAC).
    // The MessageDigest, Mac, and SecureRandom instances are created per-formatter, making this
    // class thread-confined but avoiding synchronization overhead.
    public ScramFormatter(ScramMechanism mechanism) throws NoSuchAlgorithmException {
        this.messageDigest = MessageDigest.getInstance(mechanism.hashAlgorithm());
        this.mac = Mac.getInstance(mechanism.macAlgorithm());
        this.random = new SecureRandom();
    }

    // SECURITY: SEC-SCRAM-025 (HIGH) HMAC computation using JCA Mac instance (HmacSHA256 or HmacSHA512).
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // The Mac instance is reused across calls (instance field) -- this is NOT thread-safe.
    // Each ScramFormatter instance MUST be confined to a single thread.
    // The key parameter is raw byte[] -- if key material leaks via heap dump, the HMAC can be
    // recomputed by an attacker. No key zeroization is performed after use.
    // Exploit: Heap inspection could expose the Mac key material,
    // enabling offline HMAC recomputation and credential forgery.
    // Improvement: Zero out intermediate byte arrays (clientKey,
    // storedKey) after use to minimize key material exposure.
    public byte[] hmac(byte[] key, byte[] bytes) throws InvalidKeyException {
        mac.init(new SecretKeySpec(key, mac.getAlgorithm()));
        return mac.doFinal(bytes);
    }

    public byte[] hash(byte[] str) {
        return messageDigest.digest(str);
    }

    // DECISION: XOR operates on equal-length byte arrays with explicit length check.
    // No constant-time guarantee needed here -- XOR inputs are derived crypto values, not secrets.
    public static byte[] xor(byte[] first, byte[] second) {
        if (first.length != second.length)
            throw new IllegalArgumentException("Argument arrays must be of the same length");
        byte[] result = new byte[first.length];
        for (int i = 0; i < result.length; i++)
            result[i] = (byte) (first[i] ^ second[i]);
        return result;
    }

    // SECURITY: SEC-SCRAM-026 (CRITICAL) PBKDF2 key derivation per RFC 5802 Section 5.1 (named "Hi" in the RFC).
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // Computes SaltedPassword = PBKDF2(password, salt, iterations) using the mechanism's MAC algo.
    // The salt is appended with INT(1) = [0,0,0,1] per RFC 2898 Section 5.2.
    // Minimum 4096 iterations per RFC 5802 -- enforced by caller (ScramMechanism.minIterations()),
    // NOT by this method. If iterations < 4096, brute-force resistance is significantly weakened.
    // Exploit: An attacker could brute-force weak passwords if the iteration count is set below the recommended
    // minimum.
    // Improvement: Enforce a minimum iteration count floor and consider periodic increases as hardware improves.
    public byte[] hi(byte[] str, byte[] salt, int iterations) throws InvalidKeyException {
        mac.init(new SecretKeySpec(str, mac.getAlgorithm()));
        mac.update(salt);
        byte[] u1 = mac.doFinal(new byte[]{0, 0, 0, 1});
        byte[] prev = u1;
        byte[] result = u1;
        for (int i = 2; i <= iterations; i++) {
            byte[] ui = hmac(str, prev);
            result = xor(result, ui);
            prev = ui;
        }
        return result;
    }

    public static byte[] normalize(String str) {
        return toBytes(str);
    }

    public byte[] saltedPassword(String password, byte[] salt, int iterations) throws InvalidKeyException {
        return hi(normalize(password), salt, iterations);
    }

    public byte[] clientKey(byte[] saltedPassword) throws InvalidKeyException {
        return hmac(saltedPassword, toBytes("Client Key"));
    }

    public byte[] storedKey(byte[] clientKey) {
        return hash(clientKey);
    }

    // DECISION: Username escaping per RFC 5802 Section 5.1: '=' -> '=3D', ',' -> '=2C'.
    // Uses precompiled Pattern objects (lines 42-45) for performance -- patterns are compiled
    // once and reused. The reverse mapping (username from saslName) validates that no unescaped
    // '=' characters remain after unescaping, which would indicate an invalid saslName.
    public static String saslName(String username) {
        String replace1 = EQUAL.matcher(username).replaceAll(Matcher.quoteReplacement("=3D"));
        return COMMA.matcher(replace1).replaceAll(Matcher.quoteReplacement("=2C"));
    }

    public static String username(String saslName) {
        String username = EQUAL_TWO_C.matcher(saslName).replaceAll(Matcher.quoteReplacement(","));
        if (EQUAL_THREE_D.matcher(username).replaceAll(Matcher.quoteReplacement("")).indexOf('=') >= 0) {
            throw new IllegalArgumentException("Invalid username: " + saslName);
        }
        return EQUAL_THREE_D.matcher(username).replaceAll(Matcher.quoteReplacement("="));
    }

    public static String authMessage(String clientFirstMessageBare, String serverFirstMessage, String clientFinalMessageWithoutProof) {
        return clientFirstMessageBare + "," + serverFirstMessage + "," + clientFinalMessageWithoutProof;
    }

    public byte[] clientSignature(byte[] storedKey, ClientFirstMessage clientFirstMessage, ServerFirstMessage serverFirstMessage, ClientFinalMessage clientFinalMessage) throws InvalidKeyException {
        byte[] authMessage = authMessage(clientFirstMessage, serverFirstMessage, clientFinalMessage);
        return hmac(storedKey, authMessage);
    }

    // SECURITY: SEC-SCRAM-027 (HIGH) ClientProof = ClientKey XOR ClientSignature. The XOR operation makes the proof
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // one-time-use -- knowing the ClientProof and ClientSignature allows computing ClientKey,
    // but the server only stores StoredKey = H(ClientKey), not ClientKey itself.
    // This is the core security property of SCRAM: the server never learns the ClientKey.
    // Exploit: If the iteration count is below 4096, leaked salted
    // passwords can be brute-forced at significantly higher speeds.
    // Improvement: Zero out intermediate cryptographic byte arrays
    // after use to minimize key material exposure window.
    public byte[] clientProof(byte[] saltedPassword, ClientFirstMessage clientFirstMessage, ServerFirstMessage serverFirstMessage, ClientFinalMessage clientFinalMessage) throws InvalidKeyException {
        byte[] clientKey = clientKey(saltedPassword);
        byte[] storedKey = hash(clientKey);
        byte[] clientSignature = hmac(storedKey, authMessage(clientFirstMessage, serverFirstMessage, clientFinalMessage));
        return xor(clientKey, clientSignature);
    }

    private byte[] authMessage(ClientFirstMessage clientFirstMessage, ServerFirstMessage serverFirstMessage, ClientFinalMessage clientFinalMessage) {
        return toBytes(authMessage(clientFirstMessage.clientFirstMessageBare(),
                serverFirstMessage.toMessage(),
                clientFinalMessage.clientFinalMessageWithoutProof()));
    }

    // SECURITY: SEC-SCRAM-028 (HIGH) Reconstructs StoredKey from ClientSignature and ClientProof for server-side
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // verification: StoredKey = H(ClientSignature XOR ClientProof) = H(ClientKey).
    // Used by ScramSaslServer.verifyClientProof() for constant-time comparison.
    // Exploit: If the iteration count is below 4096, leaked salted
    // passwords can be brute-forced at significantly higher speeds.
    // Improvement: Add unit tests asserting constant-time comparison
    // to prevent accidental regression to Arrays.equals().
    public byte[] storedKey(byte[] clientSignature, byte[] clientProof) {
        return hash(xor(clientSignature, clientProof));
    }

    public byte[] serverKey(byte[] saltedPassword) throws InvalidKeyException {
        return hmac(saltedPassword, toBytes("Server Key"));
    }

    public byte[] serverSignature(byte[] serverKey, ClientFirstMessage clientFirstMessage, ServerFirstMessage serverFirstMessage, ClientFinalMessage clientFinalMessage) throws InvalidKeyException {
        byte[] authMessage = authMessage(clientFirstMessage, serverFirstMessage, clientFinalMessage);
        return hmac(serverKey, authMessage);
    }

    // SECURITY: SEC-SCRAM-029 (MEDIUM) Nonce generation using SecureRandom (line 49). The nonce is represented as a
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // BigInteger with 130 random bits converted to base-36 string (~25 characters).
    // 130 bits of entropy exceeds the 128-bit minimum for cryptographic nonce security.
    // Using SecureRandom (not java.util.Random) ensures cryptographic-quality randomness.
    // Exploit: Predictable nonce or salt values would allow precomputation attacks against the challenge-response.
    // Improvement: Verify SecureRandom is seeded from a strong entropy source on the deployment platform.
    public String secureRandomString() {
        return secureRandomString(random);
    }

    public static String secureRandomString(SecureRandom random) {
        return new BigInteger(130, random).toString(Character.MAX_RADIX);
    }

    // SECURITY: SEC-SCRAM-030 (MEDIUM) Salt generation using SecureRandom. The salt is a random string converted to
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // UTF-8 bytes (~25 bytes). Per NIST SP 800-132, salt should be at least 16 bytes (128 bits).
    // The generated salt exceeds this minimum.
    // Exploit: Predictable nonce or salt values would allow precomputation attacks against the challenge-response.
    // Improvement: Verify SecureRandom is seeded from a strong entropy source on the deployment platform.
    public byte[] secureRandomBytes() {
        return secureRandomBytes(random);
    }

    public static byte[] secureRandomBytes(SecureRandom random) {
        return toBytes(secureRandomString(random));
    }

    public static byte[] toBytes(String str) {
        return str.getBytes(StandardCharsets.UTF_8);
    }

    // SECURITY: SEC-SCRAM-031 (HIGH) Credential generation from plaintext password. The password is processed through
    // Why: SCRAM cryptographic operations are the foundation of
    // challenge-response authentication security.
    // normalize() then PBKDF2 (hi). The resulting ScramCredential contains only derived values
    // (salt, storedKey, serverKey, iterations) -- the original password is NOT stored.
    // Callers should zero the password char[]/byte[] after calling this method.
    // Exploit: An attacker could brute-force weak passwords if the iteration count is set below the recommended
    // minimum.
    // Improvement: Enforce a minimum iteration count floor and consider periodic increases as hardware improves.
    public ScramCredential generateCredential(String password, int iterations) {
        try {
            byte[] salt = secureRandomBytes();
            byte[] saltedPassword = saltedPassword(password, salt, iterations);
            return generateCredential(salt, saltedPassword, iterations);
        } catch (InvalidKeyException e) {
            throw new KafkaException("Could not create credential", e);
        }
    }

    public ScramCredential generateCredential(byte[] salt, byte[] saltedPassword, int iterations) {
        try {
            byte[] clientKey = clientKey(saltedPassword);
            byte[] storedKey = storedKey(clientKey);
            byte[] serverKey = serverKey(saltedPassword);
            return new ScramCredential(salt, storedKey, serverKey, iterations);
        } catch (InvalidKeyException e) {
            throw new KafkaException("Could not create credential", e);
        }
    }
}